name: CI/CD Triage App

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 isort pytest

      # tell flake8 to allow your custom rules i.e., increased line length 
      - name: Lint with flake8
        run: flake8 --config=.flake8 .

      - name: Check formatting with black
        run: black . --check

      - name: Check import sorting with isort
        run: isort . --check-only

      - name: Run tests
        run: pytest || echo "No tests yet"